name: Build
on:
  - push
  - pull_request

concurrency: # Borrowed from https://github.com/nodejs/node/pull/42017
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "3.1"
          - "3.0"
          - "2.7"
        rails:
          - "5.1"
          - "6.0"
          - "6.1"
          - "7.0"
        exclude:
          - ruby: "2.7"
            rails: "7.0"
          - ruby: "3.0"
            rails: "5.1"
          - ruby: "3.1"
            rails: "5.1"
          - ruby: "3.1"
            rails: "6.0"
          - ruby: "3.1"
            rails: "6.1"

    runs-on: 'ubuntu-latest'

    env:
      BUNDLE_GEMFILE: gemfiles/rails${{ matrix.rails }}.gemfile
      RUBYOPT: "--disable-error_highlight"

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: bundle install
      - name: Run test suite
        run: bundle exec rake spec